names_to_order={ 
"tenrec": "Afrosoricida",
"otter shrew":"Afrosoricida",
"golden mole":"Afrosoricida",

"chevrotain":"Artiodactyla",
"deer":"Artiodactyla",
"moose":"Artiodactyla",
"caribou":"Artiodactyla",
"borckets":"Artiodactyla",
"huemel":"Artiodactyla",
"pudu":"Artiodactyla",
"muntijac":"Artiodactyla",
"bison":"Artiodactyla",
"cattle":"Artiodactyla",
"cow":"Artiodactyla",
"buffalo":"Artiodactyla",
"saola":"Artiodactyla",
"nilgai":"Artiodactyla",
"chowsingha":"Artiodactyla",
"bushbuck":"Artiodactyla",
"bongo":"Artiodactyla",
"nyala":"Artiodactyla",
"kudu":"Artiodactyla",
"sitatunga":"Artiodactyla",
"eland":"Artiodactyla",
"impala":"Artiodactyla",
"hartebeest":"Artiodactyla",
"wildebeest":"Artiodactyla",
"topi":"Artiodactyla",
"bontebok":"Artiodactyla",
"hirola":"Artiodactyla",
"antelope":"Artiodactyla",
"grysbok":"Artiodactyla",
"steenbok":"Artiodactyla",
"springbok":"Artiodactyla",
"dibatag":"Artiodactyla",
"gerenuk":"Artiodactyla",
"saiga":"Artiodactyla",
"blackbuck":"Artiodactyla",
"gazelle":"Artiodactyla",
"beira":"Artiodactyla",
"dik-dik":"Artiodactyla",
"oribi":"Artiodactyla",
"klipspringer":"Artiodactyla",
"chiru":"Artiodactyla",
"takin":"Artiodactyla",
"sheep":"Artiodactyla",
"tahr":"Artiodactyla",
"goat":"Artiodactyla",
"ibex":"Artiodactyla",
"chamois":"Artiodactyla",
"goral":"Artiodactyla",
"serows":"Artiodactyla",
"muskox":"Artiodactyla",
"duiker":"Artiodactyla",
"antelope":"Artiodactyla",
"addax":"Artiodactyla",
"oryz":"Artiodactyla",
"reedbuck":"Artiodactyla",
"kob":"Artiodactyla",
"lechwe":"Artiodactyla",
"waterbuck":"Artiodactyla",
"rhebok":"Artiodactyla",
"pronghorn":"Artiodactyla",
"giraffe":"Artiodactyla",
"okapi":"Artiodactyla",
"pig":"Artiodactyla",
"warthog":"Artiodactyla",
"bushpig":"Artiodactyla",
"hog":"Artiodactyla",
"peccary":"Artiodactyla",
"camel":"Artiodactyla",
"guanaco":"Artiodactyla",
"vicuna":"Artiodactyla",
"lama":"Artiodactyla",
"alpaca":"Artiodactyla",
"hippopotamus":"Artiodactyla",
"hippo":"Artiodactyla",

"dog":"Carnivora",
"wolf":"Carnivora",
"dhole":"Carnivora",
"fox":"Carnivora",
"bear":"Carnivora",
"panda":"Carnivora",
"raccoon":"Carnivora",
"coati":"Carnivora",
"kinkajou":"Carnivora",
"olingo":"Carnivora",
"ringtail":"Carnivora",
"skunk":"Carnivora",
"badger":"Carnivora",
"weasel":"Carnivora",
"otter":"Carnivora",
"wolverine":"Carnivora",
"tayra":"Carnivora",
"marten":"Carnivora",
"grison":"Carnivora",
"polecat":"Carnivora",
'mink':"Carnivora",
'walrus':"Carnivora",
'seal':"Carnivora",
'sea lion':"Carnivora",
'civet':"Carnivora",
'cat':"Carnivora",
'leopard':"Carnivora",
'lion':"Carnivora",
'tiger':"Carnivora",
'jaguar':"Carnivora",
'snow leopard':"Carnivora",
'puma':"Carnivora",
"jaguarundi":"Carnivora",
'cougar':"Carnivora",
'cheetah':"Carnivora",
"lynx":"Carnivora",
'serval':"Carnivora",
'linsang':"Carnivora",
'civet':"Carnivora",
'oyan':"Carnivora",
'genet':"Carnivora",
'binturong':"Carnivora",
'hyena':"Carnivora",
'aardwolf':"Carnivora",
'mongoose':"Carnivora",
'cusimanse':"Carnivora",
'meerkat':"Carnivora",
'fossa':"Carnivora",
'falanouc':"Carnivora",
'vontsira':"Carnivora",
'boky':"Carnivora",

'whale':"Cetacea",
'dolphin':"Cetacea",
'narwhal':"Cetacea",
'beluga':"Cetacea",
'porpoise':"Cetacea",

'bat':'Chiroptera',
'flying fox':'Chiroptera',

'armadilo':'Cingulata',

'marsupial mice':'Dasyuromorphia',




}